# Noctalia Fish Theme
# Generated by apply-theme.sh

set -l primary ffc799
set -l secondary 99ffe4
set -l tertiary fbadff
set -l error ff8080
set -l surface 0c0c0c
set -l on_surface ffffff
set -l on_surface_variant a0a0a0

set -g fish_color_normal $on_surface
set -g fish_color_command $primary --bold
set -g fish_color_keyword $tertiary
set -g fish_color_quote $secondary
set -g fish_color_redirection $on_surface
set -g fish_color_end $on_surface_variant
set -g fish_color_error $error
set -g fish_color_param $on_surface_variant
set -g fish_color_comment $on_surface_variant
set -g fish_color_selection --background=$primary
set -g fish_color_search_match --background=$surface_variant
set -g fish_color_operator $tertiary
set -g fish_color_escape $secondary
set -g fish_color_autosuggestion $on_surface_variant
set -g fish_color_cancel $error

set -g fish_pager_color_prefix $primary --bold --underline
set -g fish_pager_color_completion $on_surface
set -g fish_pager_color_description $on_surface_variant
set -g fish_pager_color_progress $on_surface --background=$primary
set -g fish_pager_color_selected_background --background=$surface_variant

# LS_COLORS (matching Noctalia)
# di=folder, ex=executable, ln=link, pi=pipe, so=socket, bd=block, cd=char, or=orphan, mi=missing, su=setuid, sg=setgid, tw=sticky/other-writable, ow=other-writable
set -gx LS_COLORS "di=1;38;2;255;199;153:ex=1;38;2;251;173;255:ln=38;2;153;255;228:su=0;41:sg=0;46:tw=0;42:ow=0;43"
