[colors.primary]
background = '#291c14'
foreground = '#f3f2f2'
 
[colors.cursor]
text = '#f3f2f2'
cursor = '#b6b1af' 
 
[colors.vi_mode_cursor]
text = '#291c14'
cursor = '#ea9462' 
 
[colors.search.matches]
foreground = '#37251b' 
background = '#aee74b' 
 
[colors.search.focused_match]
foreground = '#37251b' 
background = '#ea9462' 
 
[colors.footer_bar]
foreground = '#37251b' 
background = '#e8e5e3' 
 
[colors.hints.start]
foreground = '#37251b' 
background = '#e7d24b' 
 
[colors.hints.end]
foreground = '#37251b' 
background = '#e7d24b' 
 
[colors.selection]
text = '#291c14'
background = '#ea9462'
 
 
[colors.normal]
black = '#181818' 
red = '#dd641e' 
green = '#ea9462' 
yellow = '#a45528' 
blue = '#ea9462' 
magenta = '#aee74b' 
cyan = '#e7d24b' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 