color0 #291c14
color1 #dd641e
color2 #ea9462
color3 #e7d24b
color4 #aee74b
color5 #f0b28f
color6 #f0e38f
color7 #f3f2f2
color8 #746660
color9 #dd641e
color10 #ea9462
color11 #e7d24b
color12 #aee74b
color13 #f0b28f
color14 #f0e38f
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291c14
background            #291c14
foreground            #f3f2f2
selection_foreground  #b6b1af
selection_background  #37251b
active_border_color   #ea9462
inactive_border_color #37251b
url_color             #ea9462

active_tab_foreground   #251d18
active_tab_background   #ea9462
inactive_tab_foreground #b6b1af
inactive_tab_background #37251b
cursor_trail_color      #b6b1af
